Added Chainguard wolfi build

diff --git a/UBI/GDAL/Dockerfile b/UBI/GDAL/Dockerfile
--- a/UBI/GDAL/Dockerfile
+++ b/UBI/GDAL/Dockerfile
@@ -3,6 +3,16 @@ ARG platform=linux/amd64
 
 FROM --platform=${platform} registry.access.redhat.com/ubi9/ubi AS builder
 
+# Toggle selected external integrations at build time (ON/OFF)
+ARG ENABLE_OCI=ON
+ARG ENABLE_TILEDB=ON
+ARG ENABLE_SFCGAL=ON
+ARG ENABLE_NETCDF=ON
+ARG ENABLE_POSTGRESQL=ON
+ARG ENABLE_ARROW=ON
+ARG ENABLE_HDF5=ON
+ARG ENABLE_GEOS=ON
+
 # LATEST GDAL is 3.9.2 but postgis won't build
 ENV \
     ARROW_VERSION=16.1.0 \
@@ -210,19 +220,23 @@ RUN cd ${BUILD} && \
     rm -rf cgal
 
 # SFCGAL
-RUN cd ${BUILD} && \
-    mkdir sfcgal && \
-    wget -qO- https://gitlab.com/SFCGAL/SFCGAL/-/archive/v${SFCGAL_VERSION}/SFCGAL-v${SFCGAL_VERSION}.tar.gz \
-    | tar xvz -C sfcgal --strip-components=1 && \
-    cd sfcgal && \
-    sed -i 's/\bsystem\b//g' CMakeLists.txt && \
-    cmake -S . -DCMAKE_INSTALL_PREFIX=${PREFIX} -B build && \
-    cmake --build build && \
-    cmake --install build && \
-    cd build && \
-    make DESTDIR="/build_thirdparty" install && \
-    cd ${BUILD} && \
-    rm -rf sfcgal
+RUN if [ "${ENABLE_SFCGAL}" = "ON" ]; then \
+        cd ${BUILD} && \
+        mkdir sfcgal && \
+        wget -qO- https://gitlab.com/SFCGAL/SFCGAL/-/archive/v${SFCGAL_VERSION}/SFCGAL-v${SFCGAL_VERSION}.tar.gz \
+        | tar xvz -C sfcgal --strip-components=1 && \
+        cd sfcgal && \
+        sed -i 's/\bsystem\b//g' CMakeLists.txt && \
+        cmake -S . -DCMAKE_INSTALL_PREFIX=${PREFIX} -B build && \
+        cmake --build build && \
+        cmake --install build && \
+        cd build && \
+        make DESTDIR="/build_thirdparty" install && \
+        cd ${BUILD} && \
+        rm -rf sfcgal; \
+    else \
+        echo "Skipping SFCGAL build (ENABLE_SFCGAL=${ENABLE_SFCGAL})"; \
+    fi
 
 # KML
 RUN cd ${BUILD} && \
@@ -232,7 +246,10 @@ RUN cd ${BUILD} && \
     cd libkml  && \
     mkdir build && \
     cd build && \
-    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} && \
+    cmake .. \
+    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_INSTALL_PREFIX=${PREFIX} && \
     make -j$(nproc) && \
     make install && \
     make DESTDIR="/build_thirdparty" install && \
@@ -240,78 +257,98 @@ RUN cd ${BUILD} && \
     rm -rf libkml
 
 # HDF5 (FIXED: Force ZLIB detection with explicit paths)
-RUN cd ${BUILD} && \
-    wget https://github.com/HDFGroup/hdf5/releases/download/${HDF5_VERSION}/hdf5-${HDF5_VERSION}.tar.gz -O hdf5.tar.gz && \
-    tar -xvzf hdf5.tar.gz && \
-    cd hdf5-${HDF5_VERSION} && \
-    mkdir build && \
-    cmake -S . -B build \
-    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DBUILD_SHARED_LIBS=ON \
-    -DHDF5_BUILD_CPP_LIB=ON \
-    -DHDF5_BUILD_HL_LIB=ON \
-    -DHDF5_ENABLE_Z_LIB_SUPPORT=ON \
-    -DHDF5_ENABLE_ZLIB_SUPPORT=ON \
-    -DZLIB_INCLUDE_DIR=/usr/include \
-    -DZLIB_LIBRARY_RELEASE=/usr/lib64/libz.so \
-    -DZLIB_LIBRARY=/usr/lib64/libz.so \
-    && cmake --build build -j$(nproc) && \
-    cmake --install build && \
-    cmake --install build --prefix="/build_thirdparty/usr" && \
-    cd ${BUILD} && \
-    rm -rf hdf5-${HDF5_VERSION} hdf5.tar.gz
+RUN if [ "${ENABLE_HDF5}" = "ON" ]; then \
+        cd ${BUILD} && \
+        wget https://github.com/HDFGroup/hdf5/releases/download/${HDF5_VERSION}/hdf5-${HDF5_VERSION}.tar.gz -O hdf5.tar.gz && \
+        tar -xvzf hdf5.tar.gz && \
+        cd hdf5-${HDF5_VERSION} && \
+        mkdir build && \
+        cmake -S . -B build \
+        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DBUILD_SHARED_LIBS=ON \
+        -DHDF5_BUILD_CPP_LIB=ON \
+        -DHDF5_BUILD_HL_LIB=ON \
+        -DHDF5_ENABLE_Z_LIB_SUPPORT=ON \
+        -DHDF5_ENABLE_ZLIB_SUPPORT=ON \
+        -DZLIB_INCLUDE_DIR=/usr/include \
+        -DZLIB_LIBRARY_RELEASE=/usr/lib64/libz.so \
+        -DZLIB_LIBRARY=/usr/lib64/libz.so \
+        && cmake --build build -j$(nproc) && \
+        cmake --install build && \
+        cmake --install build --prefix="/build_thirdparty/usr" && \
+        cd ${BUILD} && \
+        rm -rf hdf5-${HDF5_VERSION} hdf5.tar.gz; \
+    else \
+        echo "Skipping HDF5 build (ENABLE_HDF5=${ENABLE_HDF5})"; \
+    fi
 
 # VERIFICATION STEP FOR HDF5 ZLIB SUPPORT
-RUN echo "Checking HDF5 Configuration for ZLIB..." && \
-    h5cc -showconfig | grep -i "I/O filters" && \
-    ldd $(find ${PREFIX}/lib64 ${PREFIX}/lib -name "libhdf5.so" | head -n 1) | grep libz || \
-    (echo "ERROR: ZLIB NOT LINKED PROPERLY" && exit 1)
+RUN if [ "${ENABLE_HDF5}" = "ON" ]; then \
+        echo "Checking HDF5 Configuration for ZLIB..." && \
+        h5cc -showconfig | grep -i "I/O filters" && \
+        ldd $(find ${PREFIX}/lib64 ${PREFIX}/lib -name "libhdf5.so" | head -n 1) | grep libz || \
+        (echo "ERROR: ZLIB NOT LINKED PROPERLY" && exit 1); \
+    else \
+        echo "Skipping HDF5 verification (ENABLE_HDF5=${ENABLE_HDF5})"; \
+    fi
 
 # NetCDF-C (FIXED: Explicitly point to HDF5 cmake config)
-RUN cd ${BUILD} && \
-    mkdir netcdf && \
-    wget https://downloads.unidata.ucar.edu/netcdf-c/${NETCDF_VERSION}/netcdf-c-${NETCDF_VERSION}.tar.gz -O netcdf.tar.gz && \
-    tar -xvzf netcdf.tar.gz  -C netcdf --strip-components=1 && \
-    cd netcdf && \
-    mkdir build && \
-    cd build && \
-    cmake .. \
-    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
-    -DCMAKE_INSTALL_LIBDIR=lib64 \
-    -DCMAKE_PREFIX_PATH=${PREFIX} \
-    -DHDF5_DIR=${PREFIX}/lib64/cmake/hdf5 \
-    -DBUILD_SHARED_LIBS=ON \
-    -DNETCDF_ENABLE_HDF5=ON \
-    -DENABLE_DAP=OFF \
-    -DENABLE_BYTERANGE=ON \
-    && make -j$(nproc) && \
-    make install && \
-    make DESTDIR="/build_thirdparty" install && \
-    mkdir -p /build_thirdparty/usr/lib64/cmake/netCDF && \
-    cp -r ${PREFIX}/lib64/cmake/netCDF/* /build_thirdparty/usr/lib64/cmake/netCDF/ 2>/dev/null || true && \
-    cd ${BUILD} && \
-    rm -rf netcdf netcdf.tar.gz
+RUN if [ "${ENABLE_NETCDF}" = "ON" ]; then \
+    if [ "${ENABLE_HDF5}" != "ON" ]; then \
+        echo "ERROR: ENABLE_NETCDF=ON requires ENABLE_HDF5=ON"; \
+        exit 1; \
+    fi && \
+        cd ${BUILD} && \
+        mkdir netcdf && \
+        wget https://downloads.unidata.ucar.edu/netcdf-c/${NETCDF_VERSION}/netcdf-c-${NETCDF_VERSION}.tar.gz -O netcdf.tar.gz && \
+        tar -xvzf netcdf.tar.gz  -C netcdf --strip-components=1 && \
+        cd netcdf && \
+        mkdir build && \
+        cd build && \
+        cmake .. \
+        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
+        -DCMAKE_INSTALL_LIBDIR=lib64 \
+        -DCMAKE_PREFIX_PATH=${PREFIX} \
+        -DHDF5_DIR=${PREFIX}/lib64/cmake/hdf5 \
+        -DBUILD_SHARED_LIBS=ON \
+        -DNETCDF_ENABLE_HDF5=ON \
+        -DENABLE_DAP=OFF \
+        -DENABLE_BYTERANGE=ON \
+        && make -j$(nproc) && \
+        make install && \
+        make DESTDIR="/build_thirdparty" install && \
+        mkdir -p /build_thirdparty/usr/lib64/cmake/netCDF && \
+        cp -r ${PREFIX}/lib64/cmake/netCDF/* /build_thirdparty/usr/lib64/cmake/netCDF/ 2>/dev/null || true && \
+        cd ${BUILD} && \
+        rm -rf netcdf netcdf.tar.gz; \
+    else \
+        echo "Skipping NetCDF build (ENABLE_NETCDF=${ENABLE_NETCDF})"; \
+    fi
 
 # Install Oracle Instant Client
 ARG OracleMJR
-RUN cd ${BUILD} && \
-    mkdir oic && \
-    OracleMJR=$(echo "$ORACLE_VERSION" | tr -d '.') && \
-    curl -o instantclient-basiclite.zip https://download.oracle.com/otn_software/linux/instantclient/$OracleMJR/instantclient-basic-linux.x64-${ORACLE_VERSION}dbru.zip -SL && \
-    unzip instantclient-basiclite.zip && \
-    curl -o instantclient-sdk.zip https://download.oracle.com/otn_software/linux/instantclient/$OracleMJR/instantclient-sdk-linux.x64-${ORACLE_VERSION}dbru.zip -SL && \
-    unzip -o instantclient-sdk.zip && \
-    curl -o instantclient-sqlplus.zip https://download.oracle.com/otn_software/linux/instantclient/$OracleMJR/instantclient-sqlplus-linux.x64-${ORACLE_VERSION}dbru.zip -SL && \
-    unzip -o instantclient-sqlplus.zip && \
-    mv instantclient*/ ${PREFIX}/lib64/instantclient && \
-    rm instantclient-basiclite.zip && \
-    rm instantclient-sdk.zip && \
-    rm instantclient-sqlplus.zip && \
-    echo '/usr/lib64/instantclient' | tee -a /etc/ld.so.conf.d/oracle_instantclient.conf && \
-    ldconfig && \
-    mkdir -p /build_thirdparty/usr/lib64 && \
-    cp -Pa ${PREFIX}/lib64/instantclient/. /build_thirdparty/usr/lib64/instantclient 
+RUN if [ "${ENABLE_OCI}" = "ON" ]; then \
+        cd ${BUILD} && \
+        mkdir oic && \
+        OracleMJR=$(echo "$ORACLE_VERSION" | tr -d '.') && \
+        curl -o instantclient-basiclite.zip https://download.oracle.com/otn_software/linux/instantclient/$OracleMJR/instantclient-basic-linux.x64-${ORACLE_VERSION}dbru.zip -SL && \
+        unzip instantclient-basiclite.zip && \
+        curl -o instantclient-sdk.zip https://download.oracle.com/otn_software/linux/instantclient/$OracleMJR/instantclient-sdk-linux.x64-${ORACLE_VERSION}dbru.zip -SL && \
+        unzip -o instantclient-sdk.zip && \
+        curl -o instantclient-sqlplus.zip https://download.oracle.com/otn_software/linux/instantclient/$OracleMJR/instantclient-sqlplus-linux.x64-${ORACLE_VERSION}dbru.zip -SL && \
+        unzip -o instantclient-sqlplus.zip && \
+        mv instantclient*/ ${PREFIX}/lib64/instantclient && \
+        rm instantclient-basiclite.zip && \
+        rm instantclient-sdk.zip && \
+        rm instantclient-sqlplus.zip && \
+        echo '/usr/lib64/instantclient' | tee -a /etc/ld.so.conf.d/oracle_instantclient.conf && \
+        ldconfig && \
+        mkdir -p /build_thirdparty/usr/lib64 && \
+        cp -Pa ${PREFIX}/lib64/instantclient/. /build_thirdparty/usr/lib64/instantclient; \
+    else \
+        echo "Skipping Oracle Instant Client build (ENABLE_OCI=${ENABLE_OCI})"; \
+    fi
 
 # OpenJPEG
 RUN cd ${BUILD} && \
@@ -383,18 +420,22 @@ RUN cd ${BUILD} && \
     rm -rf giflib
 
 # GEOS
-RUN cd ${BUILD} && \
-    mkdir geos && \
-    wget -qO- https://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 | tar -xvj -C geos --strip-components=1 && \
-    cd geos && \
-    cmake . \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
-    -DBUILD_TESTING=OFF && \
-    make install && \
-    make DESTDIR="/build_thirdparty" install && \
-    cd ${BUILD} && \
-    rm -rf geos
+RUN if [ "${ENABLE_GEOS}" = "ON" ]; then \
+        cd ${BUILD} && \
+        mkdir geos && \
+        wget -qO- https://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 | tar -xvj -C geos --strip-components=1 && \
+        cd geos && \
+        cmake . \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
+        -DBUILD_TESTING=OFF && \
+        make install && \
+        make DESTDIR="/build_thirdparty" install && \
+        cd ${BUILD} && \
+        rm -rf geos; \
+    else \
+        echo "Skipping GEOS build (ENABLE_GEOS=${ENABLE_GEOS})"; \
+    fi
 
 # WEbP (FIXED: Build as shared library and set correct install prefix)
 RUN cd ${BUILD} && \
@@ -514,28 +555,32 @@ RUN cd ${BUILD} && \
     rm -rf aws-sdk-cpp
 
 # TileDB
-RUN cd ${BUILD} && \
-    mkdir tiledb && \
-    wget -q https://github.com/TileDB-Inc/TileDB/archive/refs/tags/${TILEDB_VERSION}.tar.gz -O - \
-    | tar xz -C tiledb --strip-components=1 && \
-    cd tiledb && \
-    mkdir build_cmake && \
-    cd build_cmake && \
-    cmake .. \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
-    -DTILEDB_S3=OFF \
-    -DTILEDB_WERROR=OFF \
-    -DTILEDB_DISABLE_AUTO_VCPKG=TRUE \
-    -DTILEDB_TESTS=OFF \
-    -DCOMPILER_SUPPORTS_AVX2=FALSE && \
-    make -j$(nproc) && \
-    make install && \
-    make DESTDIR="/build_thirdparty" install && \
-    for i in /build_thirdparty/usr/lib64/*; do strip -s $i 2>/dev/null || /bin/true; done && \
-    for i in /build_thirdparty/usr/bin/*; do strip -s $i 2>/dev/null || /bin/true; done && \
-    cd ${BUILD} && \
-    rm -rf tiledb
+RUN if [ "${ENABLE_TILEDB}" = "ON" ]; then \
+        cd ${BUILD} && \
+        mkdir tiledb && \
+        wget -q https://github.com/TileDB-Inc/TileDB/archive/refs/tags/${TILEDB_VERSION}.tar.gz -O - \
+        | tar xz -C tiledb --strip-components=1 && \
+        cd tiledb && \
+        mkdir build_cmake && \
+        cd build_cmake && \
+        cmake .. \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
+        -DTILEDB_S3=OFF \
+        -DTILEDB_WERROR=OFF \
+        -DTILEDB_DISABLE_AUTO_VCPKG=TRUE \
+        -DTILEDB_TESTS=OFF \
+        -DCOMPILER_SUPPORTS_AVX2=FALSE && \
+        make -j$(nproc) && \
+        make install && \
+        make DESTDIR="/build_thirdparty" install && \
+        for i in /build_thirdparty/usr/lib64/*; do strip -s $i 2>/dev/null || /bin/true; done && \
+        for i in /build_thirdparty/usr/bin/*; do strip -s $i 2>/dev/null || /bin/true; done && \
+        cd ${BUILD} && \
+        rm -rf tiledb; \
+    else \
+        echo "Skipping TileDB build (ENABLE_TILEDB=${ENABLE_TILEDB})"; \
+    fi
 
 # Build real bison/flex late to keep earlier heavy layers cacheable.
 RUN cd ${BUILD} && \
@@ -583,49 +628,56 @@ $RealBin = '.';
 EOF
 
 # PostgreSQL
-RUN \
-    mkdir postgresql && \
-    wget -qO- https://ftp.postgresql.org/pub/source/v${POSTGRESQL_VERSION}/postgresql-${POSTGRESQL_VERSION}.tar.gz \
-    | tar xvz -C postgresql --strip-components=1 && \
-    cd postgresql && \
-    ./configure  --with-openssl --without-readline --prefix=$PREFIX && \
-    make install && \
-    make DESTDIR="/build_thirdparty" install && \
-    ldconfig && \
-    cd ${BUILD} && \
-    rm -rf postgresql
+RUN if [ "${ENABLE_POSTGRESQL}" = "ON" ]; then \
+        mkdir postgresql && \
+        wget -qO- https://ftp.postgresql.org/pub/source/v${POSTGRESQL_VERSION}/postgresql-${POSTGRESQL_VERSION}.tar.gz \
+        | tar xvz -C postgresql --strip-components=1 && \
+        cd postgresql && \
+        ./configure  --with-openssl --without-readline --prefix=$PREFIX && \
+        make install && \
+        make DESTDIR="/build_thirdparty" install && \
+        ldconfig && \
+        cd ${BUILD} && \
+        rm -rf postgresql; \
+    else \
+        echo "Skipping PostgreSQL build (ENABLE_POSTGRESQL=${ENABLE_POSTGRESQL})"; \
+    fi
 
 # Apache Arrow (with Parquet support)
-RUN cd ${BUILD} && \
-    mkdir arrow && \
-    wget -qO- https://github.com/apache/arrow/archive/refs/tags/apache-arrow-${ARROW_VERSION}.tar.gz \
-    | tar xvz -C arrow --strip-components=1 && \
-    cd arrow/cpp && \
-    mkdir build && \
-    cd build && \
-    cmake .. \
-    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
-    -DCMAKE_INSTALL_LIBDIR=lib64 \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
-    -DARROW_PARQUET=ON \
-    -DARROW_FILESYSTEM=ON \
-    -DARROW_DATASET=ON \
-    -DARROW_COMPUTE=OFF \
-    -DARROW_IPC=OFF \
-    -DARROW_WITH_LZ4=ON \
-    -DARROW_WITH_ZLIB=ON \
-    -DARROW_WITH_ZSTD=ON \
-    -DARROW_BUILD_SHARED=ON \
-    -DARROW_BUILD_STATIC=OFF \
-    -DARROW_JEMALLOC=OFF \
-    -DARROW_MIMALLOC=OFF \
-    -DARROW_BUILD_TESTS=OFF && \
-    make -j$(nproc) && \
-    make install && \
-    make DESTDIR="/build_thirdparty" install && \
-    cd ${BUILD} && \
-    rm -rf arrow
+RUN if [ "${ENABLE_ARROW}" = "ON" ]; then \
+        cd ${BUILD} && \
+        mkdir arrow && \
+        wget -qO- https://github.com/apache/arrow/archive/refs/tags/apache-arrow-${ARROW_VERSION}.tar.gz \
+        | tar xvz -C arrow --strip-components=1 && \
+        cd arrow/cpp && \
+        mkdir build && \
+        cd build && \
+        cmake .. \
+        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
+        -DCMAKE_INSTALL_LIBDIR=lib64 \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
+        -DARROW_PARQUET=ON \
+        -DARROW_FILESYSTEM=ON \
+        -DARROW_DATASET=ON \
+        -DARROW_COMPUTE=OFF \
+        -DARROW_IPC=OFF \
+        -DARROW_WITH_LZ4=ON \
+        -DARROW_WITH_ZLIB=ON \
+        -DARROW_WITH_ZSTD=ON \
+        -DARROW_BUILD_SHARED=ON \
+        -DARROW_BUILD_STATIC=OFF \
+        -DARROW_JEMALLOC=OFF \
+        -DARROW_MIMALLOC=OFF \
+        -DARROW_BUILD_TESTS=OFF && \
+        make -j$(nproc) && \
+        make install && \
+        make DESTDIR="/build_thirdparty" install && \
+        cd ${BUILD} && \
+        rm -rf arrow; \
+    else \
+        echo "Skipping Arrow build (ENABLE_ARROW=${ENABLE_ARROW})"; \
+    fi
 
 RUN strip -s /build_thirdparty/usr/lib64/* || /bin/true \
     && strip -s /build_proj/usr/bin/* || /bin/true
@@ -658,7 +710,7 @@ RUN if [ "${HDF4_VERSION}" != "" ] && [ "$(uname -m)" = "x86_64" ]; then \
     -DBUILD_TESTING=OFF \
     -DGDAL_USE_ARCHIVE=OFF \
     -DGDAL_USE_ARMADILLO=OFF \
-    -DGDAL_USE_ARROW=ON \
+    -DGDAL_USE_ARROW=${ENABLE_ARROW} \
     -DGDAL_USE_BASISU=OFF \
     -DGDAL_USE_BLOSC=OFF \
     -DGDAL_USE_BRUNSLI=OFF \
@@ -674,13 +726,13 @@ RUN if [ "${HDF4_VERSION}" != "" ] && [ "$(uname -m)" = "x86_64" ]; then \
     -DGDAL_USE_FYBA=OFF \
     -DGDAL_USE_GEOTIFF=ON \
     -DGDAL_USE_GEOTIFF_INTERNAL=OFF \
-    -DGDAL_USE_GEOS=ON \
+    -DGDAL_USE_GEOS=${ENABLE_GEOS} \
     -DGDAL_USE_GIF=ON \
     -DGDAL_USE_GIF_INTERNAL=OFF \
     -DGDAL_USE_GTA=OFF \
     -DGDAL_USE_HEIF=OFF \
     -DGDAL_USE_HDF4=OFF \
-    -DGDAL_USE_HDF5=OFF \
+    -DGDAL_USE_HDF5=${ENABLE_HDF5} \
     -DGDAL_USE_HDFS=OFF \
     -DGDAL_USE_ICONV=ON \
     -DGDAL_USE_IDB=OFF \
@@ -707,7 +759,7 @@ RUN if [ "${HDF4_VERSION}" != "" ] && [ "$(uname -m)" = "x86_64" ]; then \
     -DGDAL_USE_MSSQL_NCLI=OFF \
     -DGDAL_USE_MSSQL_ODBC=OFF \
     -DGDAL_USE_MYSQL=OFF \
-    -DGDAL_USE_NETCDF=ON \
+    -DGDAL_USE_NETCDF=${ENABLE_NETCDF} \
     -DNetCDF_ROOT=/usr \
     -DGDAL_USE_ODBC=OFF \
     -DGDAL_USE_ODBCCPP=OFF \
@@ -719,25 +771,25 @@ RUN if [ "${HDF4_VERSION}" != "" ] && [ "$(uname -m)" = "x86_64" ]; then \
     -DGDAL_USE_OPENJPEG=ON \
     -DGDAL_USE_OPENSSL=ON \
     -DOracle_ROOT=/usr/lib64/instantclient \
-    -DGDAL_USE_ORACLE=ON \
-    -DGDAL_USE_PARQUET=ON \
+    -DGDAL_USE_ORACLE=${ENABLE_OCI} \
+    -DGDAL_USE_PARQUET=${ENABLE_ARROW} \
     -DGDAL_USE_PCRE2=ON \
     -DGDAL_USE_PDFIUM=OFF \
     -DGDAL_USE_PNG=ON \
     -DGDAL_USE_PNG_INTERNAL=OFF \
     -DGDAL_USE_POPPLER=OFF \
-    -DGDAL_USE_POSTGRESQL=ON \
+    -DGDAL_USE_POSTGRESQL=${ENABLE_POSTGRESQL} \
     -DGDAL_USE_QHULL=OFF \
     -DGDAL_USE_QHULL_INTERNAL=OFF \
     -DGDAL_USE_RASTERLITE2=OFF \
     -DGDAL_USE_RDB=OFF \
     -DGDAL_USE_SPATIALITE=OFF \
     -DGDAL_USE_SQLITE3=ON \
-    -DGDAL_USE_SFCGAL=ON \
+    -DGDAL_USE_SFCGAL=${ENABLE_SFCGAL} \
     -DGDAL_USE_TEIGHA=OFF \
     -DGDAL_USE_TIFF=ON \
     -DGDAL_USE_TIFF_INTERNAL=OFF \
-    -DGDAL_USE_TILEDB=ON \
+    -DGDAL_USE_TILEDB=${ENABLE_TILEDB} \
     -DGDAL_USE_WEBP=ON \
     -DGDAL_USE_XERCESC=OFF \
     -DGDAL_USE_ZLIB=ON \
@@ -767,6 +819,8 @@ ARG platform=linux/amd64
 
 FROM --platform=${platform} registry1.dso.mil/ironbank/redhat/ubi/ubi9-minimal:9.4 AS runner
 
+ARG ENABLE_OCI=ON
+
 # Paths to things
 ENV \
     ORACLE_BASE=/usr/lib64/instantclient \
@@ -795,7 +849,9 @@ COPY --from=builder  /build/usr/include/ /usr/include/
 COPY --from=builder  /build_gdal_python/usr/ /usr/
 COPY --from=builder  /build_gdal_version_changing/usr/ /usr/
 
-RUN echo '/usr/lib64/instantclient' | tee -a /etc/ld.so.conf.d/oracle_instantclient.conf && \
+RUN if [ "${ENABLE_OCI}" = "ON" ]; then \
+        echo '/usr/lib64/instantclient' | tee -a /etc/ld.so.conf.d/oracle_instantclient.conf; \
+    fi && \
     ldconfig
 
 # Echo the configured GDAL formats to the build log
